language: java

jdk:
  - openjdk8

services:
    - docker

before_install:
    - docker --version

addons:
  apt:
    packages:
       - docker-ce

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

install:
    - git clone https://github.com/docker-library/official-images.git official-images

before_script:
    - image="yuwui/akatsuki"
    - if [ -n "$TRAVIS_TAG" ]; then
      image="$image:$TRAVIS_TAG";
      fi
script:
    - ./gradlew build
    - cp build/libs/Akatsuki.jar ./
    - docker build -f Dockerfile -t "$image" .
#    - official-images/test/run.sh "$image"

after_script:
    - docker inspect "$image"   
    
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -o -n "$TRAVIS_TAG" ]; then 
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$image";
    fi

notifications:
  webhooks:
    - https://circledisc-kyubey.herokuapp.com/webhook/travis
