token: super secret token
owners:
  - owner1
  - owner2
prefixes:
  - unique_prefix
games:
  - aaa
  - bbb
  - ccc
database:
  name: db name
  user: db user
  pass: db password
api:
  google: google api key
musicNodes:
  - host: example.com
    pass: mypass123
  - host: example.org
    pass: mypass123