token: super secret token
description: my super detailed bot description
owners:
  - owner1
  - owner2
prefixes:
  - unique_prefix
games:
  - aaa
  - bbb
  - ccc
database:
  name: db name
  user: db user
  pass: db password
  host: db host
api:
  google: google api key
  weebsh: weeb.sh api key
