id: bot id
token: super secret token
description: my super detailed bot description
owners:
  - owner1
  - owner2
prefixes:
  - unique_prefix
presences:
  - text: aaa
    type: streaming
  - text: bbb
    type: listening
  - text: ccc
    type: playing
  - text: ddd
    type: watching
database:
  name: db name
  user: db user
  pass: db password
  host: db host
api:
  google: google api key
  weebsh: weeb.sh api key
  discordbots: discord.bots.gg api key
  discordbotsorg: discordbots.org api key
  myanimelist: username:password
  sentry: sentry dsn
  osu: osu api key
site:
  host: your site
  ssl: false
  port: 80
backend:
  host: localhost
  ssl: false
  port: 5050
lavalink:
  - url: ws://example.com
    password: hunter2
