version: '3'

services:
  akatsuki:
    build: .

  db:
    image: postgres:alpine
    hostname: db
    environment:
      - POSTGRES_DB=akatsuki
    volumes:
      - /var/data/akatsuki-postgres-data:/var/lib/postgresql/data
