version: '3'

services:
  akatsuki:
    build: .

  akatsuki-backend:
    build: ./backend/
    hostname: backend
    ports:
      - 5050:5050

  db:
    image: postgres:alpine
    hostname: db
    environment:
      - POSTGRES_DB=akatsuki
    volumes:
      - /var/data/akatsuki-postgres-data:/var/lib/postgresql/data
