version: '3'

services:
  akatsuki:
    image: noud02/akatsuki:latest
    env_file:
      - config.env

  akatsuki-backend:
    image: noud02/akatsuki-backend:latest
    hostname: backend
    ports:
      - 5050:5050

  db:
    image: postgres:alpine
    hostname: db
    environment:
      - POSTGRES_DB=akatsuki
    volumes:
      - /var/data/akatsuki-postgres-data:/var/lib/postgresql/data
